[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JS5Hu", email = "jiashuohustu@163.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cowsay>=6.1",
    "torch>=2.14.1",
    "transformers>=5.18.0",
]

[project.scripts]
myproject = "myproject:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
